//FOLLOWING CODE IS ORIGINALLY GENERATED BY CHATGPT BUT MODIFIED BY ME
function typeEffect(element, text, delay = 80) {
    let index = 0;
    function type() {
        if (index < text.length) {
            element.textContent = element.textContent.slice(0, -1) + text[index] + "|";
            index++;
            setTimeout(type, delay);
            return
        }
        element.textContent = element.textContent.slice(0, -1)

    }
    type();
}

const observer = new IntersectionObserver(entries => {
    entries.forEach(entry => {
        if (entry.isIntersecting) {
            const element = entry.target;
            const text = element.getAttribute("type-text");
            if (!element.dataset.typed) { // Prevent multiple triggers
                element.dataset.typed = "true";
                typeEffect(element, text);
            }
        }
    });
}, { threshold: 0.5 }); // Trigger when 50% visible

// Select all elements you want to apply the typing effect to
const targets = document.querySelectorAll('.type-effect');  // Adjust the selector as needed

// Observe each element in the NodeList
targets.forEach(target => {
    observer.observe(target);
});

// Check if any element is already visible on load
window.addEventListener('load', () => {
    targets.forEach(target => {
        if (target.getBoundingClientRect().top < window.innerHeight * 0.5) {
            // Element is already visible, trigger the typing effect
            if (!target.dataset.typed) {
                target.dataset.typed = "true";
                const text = target.getAttribute("type-text");
                typeEffect(target, text);
            }
        }
    });
});
//END OF AI MODIFIED CODE